// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tagservice

import (
	api "blog_kitex/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return tagServiceServiceInfo
}

var tagServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "TagService"
	handlerType := (*api.TagService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetTagList": kitex.NewMethodInfo(getTagListHandler, newTagServiceGetTagListArgs, newTagServiceGetTagListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func getTagListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.TagServiceGetTagListArgs)
	realResult := result.(*api.TagServiceGetTagListResult)
	success, err := handler.(api.TagService).GetTagList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTagServiceGetTagListArgs() interface{} {
	return api.NewTagServiceGetTagListArgs()
}

func newTagServiceGetTagListResult() interface{} {
	return api.NewTagServiceGetTagListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetTagList(ctx context.Context, req *api.GetTagListRequest) (r *api.TagListResponse, err error) {
	var _args api.TagServiceGetTagListArgs
	_args.Req = req
	var _result api.TagServiceGetTagListResult
	if err = p.c.Call(ctx, "GetTagList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
